### ISSUE TITLE
Don't need liveness checking?

### ISSUE THREAD

**Issue by monaka** [deis/postgres#130]
It's not a bug report but just by my technical interest.

There have a readiness check in the resource controller yaml. But have no liveness check.
Does restarting Postgres make any troubles?

**Comment by bacongobbler** [comment]
Restarting postgres wouldn't be a problem, however it's an incredibly time-expensive operation since the database will need to replay all WAL logs from object storage. There hasn't really been any case where we'd need a liveness check since the bootstrapping will exit if it fails at any point, and the database replay can take either a short amount of time (under a minute) to over 30 minutes depending on the latency of the upstream object storage and how much data has been shipped over time, so we cannot set a reliable initial delay.

**Comment by monaka** [comment]
> so we cannot set a reliable initial delay.

I see. Exactly it's hard to choice it.
We can detect Database down indirectly via Controller or something. So it is less need to set.
I close this. Thanks for your answer, @bacongobbler !
